import {
    LayoutGrid,
    Users,
    SquareTerminal,
    Bot,
    BookOpen,
    BookKey,
    Settings2,
    History,
    ArrowRightLeft,
    MessageSquare,
    Plus,
    FileText,
    Building,
    MapPin,
    CreditCard,
    ShoppingBag,
    ShoppingCart,
    TrendingUp,
    BarChart3,
    Tag,
    Package,
    ShieldCheck,
    Mail,
    Globe,
    Clock,
    Layers,
    type LucideIcon,
} from 'lucide-react';

export interface CommandItem {
    id: string;
    title: string;
    description?: string;
    category: 'Pages' | 'Actions' | 'Reports' | 'Setup' | 'Admin' | 'Settings';
    parentModule: string;
    url: string;
    icon: LucideIcon;
    keywords: string[];
    shortcut?: string;
    permissions?: string[];
    roles?: string[];
}

export const COMMAND_REGISTRY: CommandItem[] = [
    // ------------------------------------------------------------------------
    // DASHBOARD & OVERVIEWS
    // ------------------------------------------------------------------------
    {
        id: 'nav-dashboard',
        title: 'Main Dashboard',
        description: 'ERP overview, daily KPIs, and quick metrics',
        category: 'Pages',
        parentModule: 'Dashboard',
        url: '/dashboard',
        icon: LayoutGrid,
        keywords: ['home', 'main', 'kpi', 'analytics', 'overview', 'dashboard'],
        shortcut: 'G D',
    },
    {
        id: 'nav-dashboard-sales',
        title: 'Sales Overview Dashboard',
        description: 'Real-time sales statistics and revenue tracking',
        category: 'Pages',
        parentModule: 'Dashboard',
        url: '/dashboard/sales',
        icon: TrendingUp,
        keywords: ['sales', 'revenue', 'overview', 'charts', 'kpi'],
    },
    {
        id: 'nav-salesman-dashboard',
        title: 'Counter / Salesman Dashboard',
        description: 'Point of sale counter metrics and staff quick views',
        category: 'Pages',
        parentModule: 'Dashboard',
        url: '/salesman/dashboard',
        icon: Bot,
        keywords: ['counter', 'saleman', 'pos', 'quick sales'],
    },
    {
        id: 'nav-investor-dashboard',
        title: 'Investor Dashboard',
        description: 'Investor portfolio, profit allocation, and capital status',
        category: 'Pages',
        parentModule: 'Dashboard',
        url: '/investor/dashboard',
        icon: BookKey,
        keywords: ['investor', 'capital', 'profit', 'equity'],
        roles: ['investor'],
    },

    // ------------------------------------------------------------------------
    // DAILY TRANSACTIONS - SALES
    // ------------------------------------------------------------------------
    {
        id: 'nav-sales-list',
        title: 'Sales List',
        description: 'View and manage all sales invoices and receipts',
        category: 'Pages',
        parentModule: 'Sales',
        url: '/sales',
        icon: ShoppingBag,
        keywords: ['sales', 'invoices', 'history', 'bills', 'orders', 'sale list'],
        shortcut: 'G S',
        permissions: ['view sales'],
    },
    {
        id: 'action-create-sale',
        title: 'Create New Sale',
        description: 'Open sales entry terminal to billing customers',
        category: 'Actions',
        parentModule: 'Sales',
        url: '/sales/create',
        icon: Plus,
        keywords: ['new sale', 'add sale', 'billing', 'invoice', 'pos', 'counter sale', 'sell'],
        shortcut: 'C S',
        permissions: ['create sales'],
    },
    {
        id: 'nav-sales-return',
        title: 'Sales Return List',
        description: 'View and process customer sales returns and credit notes',
        category: 'Pages',
        parentModule: 'Sales',
        url: '/sales-return',
        icon: ArrowRightLeft,
        keywords: ['sales return', 'customer return', 'refund', 'credit note'],
        permissions: ['view returns'],
    },
    {
        id: 'action-create-sales-return',
        title: 'Create Sales Return',
        description: 'Record returned goods from a customer',
        category: 'Actions',
        parentModule: 'Sales',
        url: '/sales-return/create',
        icon: Plus,
        keywords: ['add return', 'new sales return', 'return item'],
        permissions: ['create returns'],
    },

    // ------------------------------------------------------------------------
    // DAILY TRANSACTIONS - PURCHASES
    // ------------------------------------------------------------------------
    {
        id: 'nav-purchase-list',
        title: 'Purchase List',
        description: 'View vendor purchase orders and supplier bills',
        category: 'Pages',
        parentModule: 'Purchases',
        url: '/purchase',
        icon: ShoppingCart,
        keywords: ['purchases', 'buy', 'vendor bills', 'supplier invoices', 'procurement'],
        shortcut: 'G P',
        permissions: ['view purchases'],
    },
    {
        id: 'action-create-purchase',
        title: 'Create New Purchase',
        description: 'Record new stock inventory purchase from a supplier',
        category: 'Actions',
        parentModule: 'Purchases',
        url: '/purchase/create',
        icon: Plus,
        keywords: ['new purchase', 'buy stock', 'add purchase', 'vendor invoice'],
        shortcut: 'C P',
        permissions: ['create purchases'],
    },
    {
        id: 'nav-purchase-return',
        title: 'Purchase Return List',
        description: 'View and process vendor inventory returns',
        category: 'Pages',
        parentModule: 'Purchases',
        url: '/purchase-return',
        icon: ArrowRightLeft,
        keywords: ['purchase return', 'supplier return', 'debit note', 'return vendor'],
        permissions: ['view purchase returns'],
    },
    {
        id: 'action-create-purchase-return',
        title: 'Create Purchase Return',
        description: 'Return defective or excess stock to vendor',
        category: 'Actions',
        parentModule: 'Purchases',
        url: '/purchase-return/create',
        icon: Plus,
        keywords: ['new purchase return', 'return supplier stock'],
        permissions: ['create purchase returns'],
    },

    // ------------------------------------------------------------------------
    // PAYMENTS, CHEQUES & VOUCHERS
    // ------------------------------------------------------------------------
    {
        id: 'nav-payments-list',
        title: 'Payment & Receipt List',
        description: 'Track cash and bank voucher payments & customer receipts',
        category: 'Pages',
        parentModule: 'Payments',
        url: '/payments',
        icon: CreditCard,
        keywords: ['payments', 'receipts', 'vouchers', 'cash', 'bank', 'transactions'],
        permissions: ['view payments'],
    },
    {
        id: 'action-create-payment',
        title: 'Create Receipt | Payment',
        description: 'Record customer payment receipt or vendor payment voucher',
        category: 'Actions',
        parentModule: 'Payments',
        url: '/payments/create',
        icon: Plus,
        keywords: ['add payment', 'new receipt', 'pay vendor', 'receive cash', 'voucher'],
        shortcut: 'C R',
        permissions: ['create payments'],
    },
    {
        id: 'nav-unpaid-invoices',
        title: 'Unpaid Bills & Invoices',
        description: 'View customer outstanding balances and unpaid bills',
        category: 'Pages',
        parentModule: 'Payments',
        url: '/payments/unpaid-invoices',
        icon: Clock,
        keywords: ['unpaid', 'outstanding', 'receivables', 'due bills', 'pending payment'],
        permissions: ['view payments'],
    },
    {
        id: 'nav-cheque-clearing',
        title: 'Cheque Clearing',
        description: 'Manage clearing, deposit, and status of bank cheques',
        category: 'Pages',
        parentModule: 'Payments',
        url: '/clearing-cheque',
        icon: CreditCard,
        keywords: ['cheque clearing', 'cheque deposit', 'bank cheque', 'cleared'],
        permissions: ['manage cheques'],
    },
    {
        id: 'nav-journal-vouchers',
        title: 'Journal Vouchers (JV)',
        description: 'View double-entry financial journal vouchers',
        category: 'Pages',
        parentModule: 'Accounts',
        url: '/journal-vouchers',
        icon: FileText,
        keywords: ['journal voucher', 'jv', 'general journal', 'adjustments'],
        permissions: ['view_journal_vouchers', 'view jv'],
    },
    {
        id: 'action-create-jv',
        title: 'Create Journal Voucher',
        description: 'Post general accounting debit/credit adjustments',
        category: 'Actions',
        parentModule: 'Accounts',
        url: '/journal-vouchers/create',
        icon: Plus,
        keywords: ['new jv', 'create journal voucher', 'accounting adjustment'],
        shortcut: 'C V',
        permissions: ['create jv', 'manage jv'],
    },

    // ------------------------------------------------------------------------
    // SETUP - ACCOUNTS & MASTER DATA
    // ------------------------------------------------------------------------
    {
        id: 'nav-accounts',
        title: 'Chart of Accounts',
        description: 'Directory of customers, suppliers, banks, and ledgers',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/account',
        icon: Users,
        keywords: ['accounts', 'chart of accounts', 'customers', 'suppliers', 'parties', 'ledger'],
        shortcut: 'G A',
        permissions: ['view accounts', 'manage accounts'],
    },
    {
        id: 'action-create-account',
        title: 'Create New Account',
        description: 'Add a new customer, supplier, bank, or expense ledger',
        category: 'Actions',
        parentModule: 'Setup',
        url: '/account/create',
        icon: Plus,
        keywords: ['add customer', 'add supplier', 'new account', 'party create'],
        shortcut: 'C A',
        permissions: ['manage accounts'],
    },
    {
        id: 'nav-account-types',
        title: 'Account Types',
        description: 'Manage assets, liabilities, income, and expense classifications',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/account-types',
        icon: Layers,
        keywords: ['account types', 'head of accounts', 'nature'],
        permissions: ['manage accounts'],
    },
    {
        id: 'nav-account-categories',
        title: 'Supplier & Account Categories',
        description: 'Group accounts into trade categories and vendor segments',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/account-category',
        icon: Tag,
        keywords: ['account category', 'supplier category', 'party group'],
        permissions: ['manage accounts'],
    },

    // ------------------------------------------------------------------------
    // SETUP - ITEMS & INVENTORY
    // ------------------------------------------------------------------------
    {
        id: 'nav-items',
        title: 'Items & Products Catalog',
        description: 'Master list of inventory products, trade prices, and stock',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/items',
        icon: Package,
        keywords: ['items', 'products', 'inventory', 'stock catalog', 'goods', 'trade price'],
        shortcut: 'G I',
        permissions: ['view stock', 'manage stock'],
    },
    {
        id: 'action-create-item',
        title: 'Create New Product / Item',
        description: 'Register a new product with rate, SKU, and unit specs',
        category: 'Actions',
        parentModule: 'Setup',
        url: '/items/create',
        icon: Plus,
        keywords: ['new product', 'add item', 'create product', 'sku'],
        shortcut: 'C I',
        permissions: ['manage stock'],
    },
    {
        id: 'nav-item-categories',
        title: 'Item Categories',
        description: 'Organize products by brand, type, and product line',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/item-categories',
        icon: Tag,
        keywords: ['item category', 'product category', 'brands'],
        permissions: ['manage stock'],
    },

    // ------------------------------------------------------------------------
    // SETUP - LOCATIONS & STAFF
    // ------------------------------------------------------------------------
    {
        id: 'nav-areas',
        title: 'Areas',
        description: 'Sales geographical regions and distribution zones',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/areas',
        icon: MapPin,
        keywords: ['areas', 'zones', 'territory', 'regions'],
        permissions: ['view areas', 'edit areas'],
    },
    {
        id: 'nav-subareas',
        title: 'Subareas',
        description: 'Local neighborhood distribution boundaries',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/subareas',
        icon: MapPin,
        keywords: ['subareas', 'sectors', 'local zones'],
        permissions: ['view areas', 'edit areas'],
    },
    {
        id: 'nav-firms',
        title: 'Firms & Companies',
        description: 'Legal business entities and company branches',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/firms',
        icon: Building,
        keywords: ['firms', 'companies', 'branches', 'business units'],
        permissions: ['view firms', 'manage firms'],
    },
    {
        id: 'nav-salemen',
        title: 'Salesmen Registry',
        description: 'Manage sales representatives, commissions, and targets',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/salemen',
        icon: Users,
        keywords: ['salemen', 'sales rep', 'agents', 'staff'],
        permissions: ['manage staff'],
    },
    {
        id: 'nav-chequebooks',
        title: 'Cheque Books',
        description: 'Register bank cheque book leafs and active series',
        category: 'Setup',
        parentModule: 'Setup',
        url: '/cheque',
        icon: CreditCard,
        keywords: ['cheque books', 'bank cheques', 'leafs'],
        permissions: ['manage cheques'],
    },
    {
        id: 'nav-offer-list',
        title: 'Offer List',
        description: 'Special trade promotion offers and price lists',
        category: 'Pages',
        parentModule: 'Sales',
        url: '/offer-list',
        icon: Tag,
        keywords: ['offers', 'discounts', 'promotions', 'price list'],
        permissions: ['view sales'],
    },

    // ------------------------------------------------------------------------
    // ORDERS & SUPPLIER MANAGEMENT
    // ------------------------------------------------------------------------
    {
        id: 'nav-supplier-orders',
        title: 'Supplier Orders List',
        description: 'View purchase orders sent to supplier companies',
        category: 'Pages',
        parentModule: 'Orders',
        url: '/admin/supplier-order/list',
        icon: ShoppingCart,
        keywords: ['supplier orders', 'po list', 'vendor orders'],
        permissions: ['view purchases'],
    },
    {
        id: 'action-create-supplier-order',
        title: 'Create Supplier Order',
        description: 'Generate purchase order for wholesale suppliers',
        category: 'Actions',
        parentModule: 'Orders',
        url: '/admin/supplier-order',
        icon: Plus,
        keywords: ['create supplier order', 'new po', 'order inventory'],
        permissions: ['create purchases'],
    },

    // ------------------------------------------------------------------------
    // REPORTS & ANALYTICS
    // ------------------------------------------------------------------------
    {
        id: 'nav-reports-analytics',
        title: 'Analytics & Intelligence Report',
        description: 'Executive financial insights, trends, and growth indicators',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/analytics',
        icon: BarChart3,
        keywords: ['analytics', 'intelligence', 'charts', 'trends', 'reports'],
        shortcut: 'G R',
        permissions: ['view reports'],
    },
    {
        id: 'nav-reports-ledger',
        title: 'Accounts Ledger Report',
        description: 'General ledger statements and party balance details',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/accounts/ledger',
        icon: BookOpen,
        keywords: ['ledger report', 'account statement', 'party balance', 'audit ledger'],
        permissions: ['view reports'],
    },
    {
        id: 'nav-reports-stock',
        title: 'Stock & Inventory Report',
        description: 'Current stock position, valuation, and ledger movements',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/stock',
        icon: Package,
        keywords: ['stock report', 'inventory valuation', 'available stock'],
        permissions: ['view reports'],
    },
    {
        id: 'nav-reports-sales',
        title: 'Sales Summary & Detailed Report',
        description: 'Periodical sales performance, customer breakdowns, and margins',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/sales',
        icon: TrendingUp,
        keywords: ['sales report', 'revenue report', 'daily sales report'],
        permissions: ['view reports'],
    },
    {
        id: 'nav-reports-purchase',
        title: 'Purchase Summary Report',
        description: 'Vendor purchase breakdowns, item receipts, and totals',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/purchase',
        icon: ShoppingCart,
        keywords: ['purchase report', 'buying report', 'vendor purchases'],
        permissions: ['view reports'],
    },
    {
        id: 'nav-reports-profit',
        title: 'Profitability Report',
        description: 'Gross and net profit margins per item and transaction',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/profit',
        icon: TrendingUp,
        keywords: ['profit report', 'margins', 'net profit', 'gross profit'],
        permissions: ['view profit reports'],
    },
    {
        id: 'nav-reports-audit',
        title: 'System Audit Report',
        description: 'Audit logs of deleted, modified, and overridden records',
        category: 'Reports',
        parentModule: 'Reports',
        url: '/reports/audit',
        icon: ShieldCheck,
        keywords: ['audit report', 'log audit', 'security audit'],
        permissions: ['view reports'],
    },

    // ------------------------------------------------------------------------
    // ADMINISTRATION & INVESTOR MANAGEMENT
    // ------------------------------------------------------------------------
    {
        id: 'nav-staff',
        title: 'Staff Directory',
        description: 'Employee profiles, system users, and job assignments',
        category: 'Admin',
        parentModule: 'Administration',
        url: '/staff',
        icon: Users,
        keywords: ['staff', 'employees', 'users', 'team'],
        permissions: ['manage staff'],
    },
    {
        id: 'nav-shifts',
        title: 'Work Shifts Management',
        description: 'Staff working hours, shift timers, and break limits',
        category: 'Admin',
        parentModule: 'Administration',
        url: '/admin/shifts',
        icon: Clock,
        keywords: ['shifts', 'timing', 'work hours', 'timer'],
        permissions: ['manage staff'],
    },
    {
        id: 'nav-roles-permissions',
        title: 'Roles & Permission Center',
        description: 'Assign user privileges, access rules, and security roles',
        category: 'Admin',
        parentModule: 'Administration',
        url: '/roles/permissions',
        icon: ShieldCheck,
        keywords: ['roles', 'permissions', 'access control', 'security'],
        permissions: ['manage roles', 'manage permissions'],
    },
    {
        id: 'nav-activity-logs',
        title: 'System Activity Logs',
        description: 'Audit trails of user actions and record edits',
        category: 'Admin',
        parentModule: 'Administration',
        url: '/admin/activity-logs',
        icon: History,
        keywords: ['activity logs', 'user actions', 'audit log', 'history'],
        permissions: ['manage roles'],
    },
    {
        id: 'nav-admin-investors',
        title: 'Investors Management',
        description: 'Manage investor accounts, capital allocations, and equity',
        category: 'Admin',
        parentModule: 'Investor Management',
        url: '/admin/investors',
        icon: BookKey,
        keywords: ['investors', 'capital management', 'equity distribution'],
        permissions: ['manage roles'],
    },
    {
        id: 'nav-profit-distribute',
        title: 'Profit Distribution',
        description: 'Calculate and post profit dividends to business investors',
        category: 'Admin',
        parentModule: 'Investor Management',
        url: '/admin/profit/distribute',
        icon: TrendingUp,
        keywords: ['profit distribution', 'dividends', 'investor share'],
        permissions: ['manage roles'],
    },

    // ------------------------------------------------------------------------
    // SETTINGS
    // ------------------------------------------------------------------------
    {
        id: 'nav-settings-email',
        title: 'Email Configuration',
        description: 'Configure SMTP mail servers, ports, and default sender details',
        category: 'Settings',
        parentModule: 'Settings',
        url: '/admin/settings/email',
        icon: Mail,
        keywords: ['email settings', 'smtp', 'mail config'],
        permissions: ['manage permissions', 'manage roles'],
    },
    {
        id: 'nav-settings-system',
        title: 'System Configuration',
        description: 'ERP company identity, currency formatting, and site behavior',
        category: 'Settings',
        parentModule: 'Settings',
        url: '/admin/settings/configuration',
        icon: Settings2,
        keywords: ['system settings', 'company config', 'general settings'],
        permissions: ['manage permissions', 'manage roles'],
    },
    {
        id: 'nav-settings-templates',
        title: 'Email Templates',
        description: 'Customize automated customer receipts and invoice notification emails',
        category: 'Settings',
        parentModule: 'Settings',
        url: '/admin/settings/templates',
        icon: FileText,
        keywords: ['email templates', 'mail notifications', 'templates'],
        permissions: ['manage permissions', 'manage roles'],
    },
    {
        id: 'nav-settings-countries',
        title: 'Countries Master',
        description: 'Country definitions and regional trade settings',
        category: 'Settings',
        parentModule: 'Settings',
        url: '/countries',
        icon: Globe,
        keywords: ['countries', 'nations', 'geography'],
        permissions: ['manage permissions', 'manage roles'],
    },
    {
        id: 'nav-notifications-center',
        title: 'Notification Center',
        description: 'View system alerts, approval requests, and notifications',
        category: 'Pages',
        parentModule: 'System',
        url: '/notifications',
        icon: MessageSquare,
        keywords: ['notifications', 'alerts', 'messages', 'inbox'],
        shortcut: 'G N',
    },
];
